articles/api-plugin-output.md, articles/api-plugin-parser.md, articles/extract-section.md, articles/http-to-td.md, articles/inject-section.md, articles/multi-process-workers.md, configuration/buffer-section.md, configuration/config-file.md, configuration/format-section.md, configuration/parse-section.md, deployment/plugin-management.md, plugins/filter/geoip.md, plugins/filter/grep.md, plugins/filter/parser.md, plugins/filter/record_transformer.md, plugins/filter/stdout.md, plugins/formatter/json.md, plugins/formatter/msgpack.md, plugins/input/forward.md, plugins/input/syslog.md, plugins/input/tail.md, plugins/input/tcp.md, plugins/input/udp.md, plugins/output/README.md, plugins/output/elasticsearch.md, plugins/output/file.md, plugins/output/forward.md, plugins/output/stdout.md, plugins/parser/regexp.md
This is a collection of patches for v1.0 articles since https://github.com/fluent/fluentd-docs/commit/6dad0eab466889ccae9972145f7e9054680a1c15
Since the directory layout has been changed, I have applied
each patch manually one by one, fixing their contents to fit the
GitBook style formatting.
With this, the v1.0 documentation should sync with v1.4.2.
=> Apply pending changes to  v1.0 articles

overview/post-installation-guide.md
This imports a fix from fluent/fluentd-docs. For details,
please follow the link below:
https://github.com/fluent/fluentd-docs/commit/2e23a10
=> overview: import a fix from the old documentation

plugins/input/README.md, plugins/input/unix.md
Right now GitBook site lacks the manual for in_unix. So I bring the
manual document from the old site, and migrates the content to
GitBook format.
=> plugins: input: Add documentation for in_unix

overview/update-from-v0.12.md, plugins/input/unix.md, plugins/output/README.md
This is a collections of fixes for broken links I found while
reading the new GitBook site.
=> Fix broken links in the Gitbook documentations

plugins/filter/grep.md, plugins/input/forward.md, plugins/input/syslog.md, plugins/input/tail.md, plugins/input/tcp.md, plugins/input/udp.md, plugins/output/copy.md, plugins/output/exec_filter.md, plugins/output/file.md, plugins/output/mongo.md, plugins/output/mongo_replset.md, plugins/output/rewrite_tag_filter.md, plugins/output/roundrobin.md, plugins/output/s3.md, plugins/output/webhdfs.md, plugins/parser/regexp.md, plugins/parser/syslog.md
Gitbook won't recognize `\<` or `\>` as escaped brackets, and
will embed them as is. This breaks the rendered HTML.
This patch fixes these wrong escapes to use backticks instead.
=> Escape <> brackets properly

configuration/buffer-section.md, configuration/extract-section.md, configuration/format-section.md, configuration/inject-section.md, configuration/parse-section.md
Evidently GitBook renders line breaks in bullet lists as <br>.
For example, think about the following text:
- This is printed
in two lines???
This breaks the layout of a few documents. This patch should
fix them.
=> config-file: fix broken line wraps in bullet lists.

plugins/input/tail.md
* Fix broken line wrapping
* Escape special characters proprely
=> in_tail: use more consistent text formatting.

plugins/input/tail.md
This is a collection of minor styling fixes that should make the
document rendered nicely in GitBook.
=> in_tail: More fixes on text stylings

guides/parse-syslog.md, plugins/output/forward.md
This patch contains the changesets made by:
* https://github.com/fluent/fluentd-docs/pull/632
* https://github.com/fluent/fluentd-docs/pull/634
* https://github.com/fluent/fluentd-docs/pull/633
=> Sync changes in fluent/fluentd-docs

deployment/performance-tuning-single-process.md, developer/api-plugin-formatter.md, guides/splunk-like-grep-and-alert-email.md, install/post-installation-guide.md, overview/quickstart.md, plugins/input/http.md, plugins/output/webhdfs.md
These internal links were broken due to the migration to GitBook.
Also, let's prefer HTTPS over HTTP whenever possible.
=> Fix a few more broken links

.gitbook.yaml
Previously, the index page of the documentation was hosted at:
https://docs.fluentd.org/v1.0/articles/quickstart
The problem is that, due to the migration to GitBook, no page
exists at that URL anymore. Still, Google and others are showing
results that point to the URL.
In order to solve this issue, I added .gitbook.yaml, which should
redirect users who access to /v1.0/articles/quickstart to the
current index page.
=> Add .gitbook.yaml to navigate users from /v1.0/articles/quickstart

.gitbook.yaml
Signed-off-by: jordo1138 <8525512+jordo1138@users.noreply.github.com>
see #27 , just a test example to do the redirects from your existing .gitbook.yaml , seems like most v1 articles follow ```v1.0/articles/name-of-guide``` and then redirect to ```guides/name-of-guide.md``` 
if the guide exists in /guides in the repo...actual guides uri is ```how-to-guides```
additional seo redirects could be done also as mentioned
=> add additonal redirect

guides/cep-norikra.md
Also this modifies links to use HTTPS over HTTP as possible.
=> cap-norikura: fix obsolete/broken links

.gitbook.yaml
A deployment error occured in the parent commit (test 3).
This tests the hypothesis that GitBook's YAML parser mishandles
the literal string "null".
=> gitbook: debug deploy problem (4)

.gitbook.yaml
The deployment failed on test 8. While reviewing it, I noticed that
some entries are defined twice in redirections.
This removes a duplicated entry from the list.
=> gitbook: debug deploy problem (9)

SUMMARY.md, overview/td-agent-v2-vs-v3.md
While updating the redirection mapping, I noticed the article is
missing from the new site.
Let's migrate it from the old doc repository.
=> overview: add a missing article "td-agent v2 vs v3"

.gitbook.yaml
I noticed some URLs are missing from the mapping defintion while
reviewing the access logs (for the old doc site). This should
fixes it.
=> Add more redirections to .gitbook.yaml

.gitbook.yaml
This reorders the URL list, and add block comments to it to make
management easier.
=> Organize the list of URLs in .gitbook.yaml

.gitbook.yaml
This article was added in 009771c, and was not on the list yet.
This patch should fix it.
=> Add the redirect definition for "overview/td-agent-v2-vs-v3.md"

developer/api-plugin-parser.md
```
root@xxxxx:/var/log/td-agent# /opt/td-agent/embedded/bin/fluentd --log /var/log/td-agent/td-agent.log --daemon /var/run/td-agent/td-agent.pid $TD_AGENT_OPTIONS
/etc/td-agent/plugin/parser_xxx.rb:16:in `configure': uninitialized constant Fluent::Plugin::XXX::TimeParser (NameError)
Did you mean?  Fluent::TimeParser
```
=> Module name needs to be included for TimeParser

plugins/input/http.md, plugins/input/syslog.md, plugins/input/tcp.md
docs for https://github.com/fluent/fluentd/pull/2395 and in_tcp
@repeatedly could you review this, please?
cc. @edsiper
=> Add tcp and http doc

configuration/buffer-section.md
This PR fixes the default value of `queued_chunks_limit_size` based on following PR.
https://github.com/fluent/fluentd/pull/2173
=> Fix the default value of queued_chunks_limit_size

configuration/parse-section.md
=> Fix default value of time_type for parse-section

plugins/output/forward.md
there is a small typo: `tls_client_cert_pat` is `tls_client_cert_path`
=> Correct config for tls_client_cert_path

guides/apache-to-mongodb.md, guides/apache-to-s3.md, guides/free-alternative-to-splunk-by-fluentd.md, guides/http-to-hdfs.md, guides/http-to-td.md, guides/kinesis-stream.md, install/install-by-deb.md, install/install-by-rpm.md
It seems necessary to add `https:` to www.fluentd.org link.
To fix https://github.com/fluent/fluentd-docs-gitbook/issues/65
cc @repeatedly
=> Add https to all www.fluentd.org link

configuration/config-file.md
- There were no code block backticks around example code, which was causing it to not display correctly in the docs.
=> Added code block around embedding Ruby example

plugins/buffer/README.md
the image is not show up in webpage https://docs.fluentd.org/buffer
This PR try to fix it
=> update image markdown link to make it show in website

developer/api-config-types.md
`default: :udp` instead of `default: udp` - which would fail with `NameError (undefined local variable or method 'udp' for main:Object)`
=> Make :udp a symbol

guides/http-to-hdfs.md
As of today, it is Hadoop 3 and CDH6.
Also fix Cloudera's Download page URL.
=> Remove Hadoop version 1 and CDH3/4 as outdated

configuration/buffer-section.md
This PR fixes the wrong parameter name of queued_chunks_limit_size's default value.
=> Fix parameter name of default value

plugins/filter/parser.md
This was removed in https://github.com/fluent/fluentd-docs-gitbook/pull/95 but that is incorrect.
The second bracket is required because the first `]` is escaped with `\` because the regex is looking for the next `]` before the `time` attribute is set. The second is what closes the character class.
The example the message is trying to parse is 
>[05/Feb/2018:12:00:00 +0900]
So this: `\[(?<time>[^\]*)\]` is invalid because there are two `[` and one `]` **and** one literal `]`
See this [original](https://fluentular.herokuapp.com/parse?regexp=%5E%28%3F%3Chost%3E%5B%5E+%5D*%29+%5B%5E+%5D*+%28%3F%3Cuser%3E%5B%5E+%5D*%29+%5C%5B%28%3F%3Ctime%3E%5B%5E%5C%5D*%29%5C%5D+%22%28%3F%3Cmethod%3E%5CS%2B%29%28%3F%3A+%2B%28%3F%3Cpath%3E%5B%5E+%5D*%29+%2B%5CS*%29%3F%22+%28%3F%3Ccode%3E%5B%5E+%5D*%29+%28%3F%3 …
=> Added required bracket back

developer/api-plugin-helper-socket.md
I've found that mutual authentication parameters are not documented.
=> Add private_key_path and private_key_passphrase parameters

deployment/logging.md
Windows does not permit delete and rename files which are owned by another process.
And Fluentd v1.7.4 will split log files when logrotate feature is
enabled on Windows.
=> Add notes logrotation on Windows

deployment/monitoring-prometheus.md
The version installed by the command has been verified as version 1.0.1.  
(in fluent/fluentd:edge Container) But Version 1.0.1 gives the error as   `invalid argument`.
**If specify version 1.0.0 as 1.6.1, no error occurs.**  
The same issue has been reported in [this repository](https://github.com/fluent/fluentd-kubernetes-daemonset/issues/361).
tested in Windows 10 Pro(1903, 18362.476 Build) / DockerDesktop( 2.1.0.5 version)
=> Change fluent-plugin-prometheus version to 1.6.1

configuration/buffer-section.md, configuration/parse-section.md
I fixed some broken links.
* `v0.12 compatibility` of https://docs.fluentd.org/configuration/buffer-section
* `json, ltsv and regexp` of https://docs.fluentd.org/configuration/parse-section
=> fix some links 

developer/plugin-development.md
Fix broken slides link in gitbook at https://docs.fluentd.org/plugin-development#overview
=> Fix broken slides link in plugin-development

install/post-installation-guide.md
On `/installation/post-installation-guide`, the word Apache was spelled incorrectly.
=> fix: Change Aapche to Apache

developer/api-plugin-helper-http_server.md
ref: https://github.com/fluent/fluentd/pull/2787
=> Add https server document

plugins/input/tail.md
ref https://github.com/fluent/fluentd/issues/1126, https://github.com/fluent/fluentd/pull/2805
=> Add auto-compaction doc

README.md
Gitbook is having issues. and it took me a while to figure out the docs were available in this repo just under their fluentd version tag https://github.com/fluent/fluentd-docs-gitbook/issues/149
This PR adds the link to the revisions alongside the gitbook link
=> add branches links to main README

install/install-by-gem.md
Signed-off-by: Christian Lacsina <christian.lacsina@rx-m.com>
Ruby Gem installation docs still list Ruby 2.1 as the minimum version. Minimum version is now Ruby 2.4 according to https://www.fluentd.org/blog/drop-schedule-announcement-in-2019
=> update gem install doc to reflect Ruby 2.4 support

plugins/input/forward.md
`parser` filter plugin is already included in fluentd core.
So, I fix document path for parser filter plugin.
=> Fix document path for parser filter

plugins/service_discovery/file.md, plugins/service_discovery/srv.md
configuration examples in service discovery examples use in_forward; update to out_forward
=> update config examples to use out_forward instead of in_forward in service discovery 

plugins/filter/record_transformer.md
This PR adds an additional example for `record_transformer`. It covers the usage of the `remove_keys`, including the removal of a nested key.
=> Add example of 'remove_keys' including nested keys

plugins/input/syslog.md
RFC-6587 defines the syslog frame as:
```
SYSLOG-FRAME = MSG-LEN SP SYSLOG-MSG
```
Thus the `MSG-LEN` should not include the space.
=> Fix message length

plugins/filter/geoip.md
I noticed that, the code example in `https://docs.fluentd.org/filter/geoip` about the use case of `country_code` starts with a `<filter>` tag but closes with `</match>` tag.
=> Fix geoip code example

plugins/output/http.md
Related to https://github.com/fluent/fluentd/issues/3022 and https://github.com/fluent/fluentd/pull/2973.
=> out_http: json_array documentation

install/install-by-msi.md
It omits manual registration step as Windows service.
=> Update windows install steps for 4.0.0

deployment/rpc.md
I found if config fluentd with --no-supervisor, rpc flunction will failed
=> rpc require fluentd start not with --no-supervisor

guides/free-alternative-to-splunk-by-fluentd.md
Fixing minor typo in the Elasticsearch documentation page.
=> Fix Elasticsearch setup doc typo

plugins/filter/parser.md
`replace_invalid_sequence` description table is broken.
=> filter_parser: Fix a broken table

configuration/buffer-section.md
It seems that overflow_action block is used out-of-scope case, such
as avoiding high CPU usage. It is definitely wrong usage, but
known as a some sort of technique.
=> buffer-section: update overflow_action block explanation

plugins/output/rewrite_tag_filter.md
The pattern should be `/^\[(\w+)\]/`. From the record `{"message":"[info]: ..."} `, the line starts with `[`, instead of the word `info`.
FYI: https://github.com/fluent/fluent-plugin-rewrite-tag-filter/issues/103
=> rewrite_tag_filter: Fix the incorrect pattern

.gitbook.yaml, configuration/linux-capability.md, plugins/input/tail.md
Related to https://github.com/fluent/fluentd/pull/3155
=> 1.0: Add linux capability descriptions

plugins/output/elasticsearch.md
This PR adds two minor documentation improvements:
- Improve wording about bulk indexing and point to ES bulk api docs
- Add link to buffer section on spot so as to have easier access to buffer options documentation.
=> Improve elasticsearch output docs

configuration/linux-capability.md
Please merge this PR after #248 is merged.
Related to https://github.com/fluent/fluentd/pull/3162.
=> 1.0: Use fluent-cap-ctl to handle capabilities

filter/geoip.md, how-to-guides/free-alternative-to-splunk-by-fluentd.md
Minor typo fix, from ElasticSearch to Elasticsearch.
=> Fix ElasticSearch → Elasticsearch

configuration/inject-section.md
This PR adds the time types introduced by https://github.com/fluent/fluentd/pull/3220 to time parameters.
=> Add unixtime_millis, unixtime_micros and unixtime_nanos

input/sample.md
The example doesn't work as-is, as it's missing the required parameter 'tag'.
=> input/sample example - add tag

deployment/command-line-option.md
Corresponds to https://github.com/fluent/fluentd/pull/3240.
=> 1.0: plugin-config-format: Add markdown table output style description

deployment/command-line-option.md, deployment/system-config.md
In addition, add some missing command line options.
=> Add new system config `disable_shared_socket` as of Fluentd 1.12.1

parser/apache2.md
Since https://github.com/fluent/fluentd/commit/df5ac352f916c1118fba0ddd61cf6cea2b4a1b70 , the regex has been updated. The one provided in docs will actually fail to match certain Apache logs.
=> Update regex in apache2 parser plugin

plugin-development/api-plugin-parser.md
=> 1.0: link to overview of parser instead of missing document

SUMMARY.md, deployment/linux-capability.md, filter/geoip.md, how-to-guides/free-alternative-to-splunk-by-fluentd.md, how-to-guides/syslog-influxdb.md, input/tail.md, installation/install-by-dmg.md, output/s3.md, plugin-development/api-config-types.md, plugin-helper-overview/api-plugin-helper-inject.md, plugin-helper-overview/api-plugin-helper-socket.md, plugins/input/dummy.md, quickstart/faq.md, quickstart/td-agent-v2-vs-v3-vs-v4.md, service_discovery/srv.md
Apple's operating system used to be called "Mac OS X" or "OS X" for short, but since 2016 is known as "macOS." This PR includes that update, as well as a few minor typo fixes.
=> Update "OS X" to "macOS" and correct minor typos

formatter/ltsv.md, output/copy.md
I added descriptions for the features that we added in v1.12.2,
but have not yet documented.
With this merged, docs.fluentd.org should be keep in line with
the latest release. For details, see:
https://www.fluentd.org/blog/fluentd-v1.12.2-has-been-released
Signed-off-by: Fujimoto Seiji <fujimoto@ceptord.net>
=> Document new plugin features in v1.12.2

parser/ltsv.md
This reverts commit #292 (1368ae294d6a076e2b8fc9efa93bfd2cf5e8b70c).
Because it's wrogly added to the parser_ltsv page.
The formatter_ltsv page has been updated at #295 (21a85bbf7e32ccfab42e624b289edd5bbf4f685d).
=> Revert "Add replacement config for formatter_ltsv"

language-bindings/php.md
It should be PHP 5.6 or later.
ref. https://github.com/fluent/fluent-logger-php/blob/master/composer.json
Closes: #293
Signed-off-by: Kentaro Hayashi <kenhys@gmail.com>
=> 1.0: Update outdated PHP version

deployment/fluentd-ui.md
Although same links are still remained in installation/install-by-rpm.md
and installation/install-by-deb.md, they shouldn't be fixed yet because
they are example of systemd's output. We'll fix the system unit file
before replacing them:
https://github.com/fluent-plugins-nursery/td-agent-builder/pull/298
Signed-off-by: Takuro Ashie <ashie@clear-code.com>
=> Fix a broken link to td-agent website

how-to-guides/graylog2.md
`0.0.0.0` is invalid as a destination address.
The original patch is posted by Alex Heylin <alexh@gmal.co.uk> in
https://github.com/fluent/fluentd-docs-gitbook/pull/141
Thanks!
Signed-off-by: Takuro Ashie <ashie@clear-code.com>
=> Fix a wrong destination address in graylog example

installation/install-by-msi.md
`td-agent` is under-explained in the current guide, but it is easy to
understand in the context of Windows: It's a standalone package of
Fluentd that includes all the required dependencies.
Let's explain that, instead of telling users to read another article.
Signed-off-by: Fujimoto Seiji <fujimoto@ceptord.net>
=> installation: Add a short introduction of td-agent

configuration/buffer-section.md
There are needless escape characters `\`.
=> 1.0: fix broken markup in Buffer Section

input/tail.md
Documentation for https://github.com/fluent/fluentd/pull/3185.
=> 1.0: in_tail: Add read_bytes_limit_per_second description

deployment/system-config.md
This configuration is mainly introduced to customize log rotation
settings on Windows (in a more comprehensive way).
Since implemented as system configuration,
this feature is supported on other platforms too.
=> 1.0: Document rotate_age and rotate_size in system config section

container-deployment/docker-compose.md
https://docs.docker.com/compose/compose-file/#/logging
is moved to the specific version of the logging section.
https://docs.docker.com/compose/compose-file/compose-file-v3/#logging
https://docs.docker.com/compose/compose-file/compose-file-v2/#logging
In our example, it uses v3 version, so it should be
https://docs.docker.com/compose/compose-file/compose-file-v3/#logging
=> 1.0: update compose logging link

installation/before-install.md
This is usual software vulnerabilities for hardlink/symlink.
Fluentd sometimes uses symlink and predictable paths.
Predictable paths always are used in sigdump.
Which is known vulnerability of Fluentd agent.
Specifying `fs.protected_hardlinks` and `fs.protected_symlinks` to be set
up as `1` is popular approach to mitigate this vulnerability.
Signed-off-by: Hiroshi Hatake <hatake@calyptia.com>
=> 1.0: Mitigate descriptions for hardlink/symlink attack

monitoring-fluentd/monitoring-prometheus.md
Without the fix, Fluentd does not start and logs an error
...
`error_class=Fluent::ConfigError error="'host' parameter is required, in section server"`
...
The change adjusts to what is in the current master in the linked example
https://github.com/kzk/fluentd-prometheus-config-example/blob/c03d7797606c63830ebd6715d223ede282f19e34/fluentd.conf#L28
=> Fix: Change hostname to host

input/http.md
I added missing `use_204_response`.
- Fluentd Pull Request: 
- https://github.com/fluent/fluentd/pull/2640
- Commit: 
- https://github.com/fluent/fluentd/commit/ee2ae7b0178ec1f13e53ff18d35e7b5818bc55b1
- It means the option is supported from v1.8.0
- Note:
- The option will be deprecated at v2. See also https://github.com/fluent/fluentd/pull/2640#issuecomment-539439936
=> in_http: add use_204_response

container-deployment/docker-compose.md
What:
Updating version 1.0 of the documentation to reflect new gem and container versions
Where:
docker-compose.md
fluend gem version
elasticsearch container version
kibana container version
Why:
Keeping the documentation page up to date with example code repo in the documentation 
[https://github.com/digikin/fluentd-elastic-kibana](https://github.com/digikin/fluentd-elastic-kibana)
=> 1.0  updating document code to reflect new fluend, elastic and kibana container versions

filter/parser.md
Closes: #334
It will help to understand the behavior of reesrve_time.
=> Explain reserve_time with an execution result
