fluent/fluentd-docs-gitbook

articles/raspberrypi-cloud-data-logger.txt
This article also has not been migrated to GitBook yet.
I migrated the content and styling to the GitBook format, so
it should look fine on the new site.
=> articles: Migrates "Cloud Data Logger by Raspberry Pi"

SUMMARY.md, guides/http-to-hdfs.md, overview/faq.md, overview/quickstart.md, overview/update-from-v0.12.md, plugins/input/udp.md
While reviewing the new site, I noticed a few more broken links.
This is a collection of fixes for them.
=> Fix broken links and missing articles

.gitbook.yaml
The parent commit was deployed successfully. Let's continue the
testing. This adds a redirection which contains a hyphen in its URL.
=> gitbook: debug deploy problem (2)

plugins/output/file.md
=> fix link of plugins/output/file.md

developer/api-plugin-helper-http_server.md, developer/plugin-helper-overview.md
ref: https://github.com/fluent/fluentd/pull/2447
=> Add http server helper document

.gitbook.yaml, SUMMARY.md, developer/api-plugin-helper-http_server.md
I found some missing things about http_server document.
cc. @repeatedly
=> Fix http server docs

plugins/output/elasticsearch.md
close https://github.com/fluent/fluentd-docs-gitbook/issues/52
cc. @repeatedly
=> guides -> developer

developer/api-plugin-helper-http_server.md
ref: https://github.com/fluent/fluentd/pull/2493
=> Add title arguments

configuration/inject-section.md
Signed-off-by: Vivek Chandrasekhar <vivekchandrasekhar@yahoo.com>
=> just fixed a typo

plugins/output/README.md
Signed-off-by: Chris Pedro <chris@thepedros.com>
=> Added secondary output example for buffers

developer/logo.md
follow up https://github.com/fluent/fluentd-docs-gitbook/pull/86
=> "pubic" is unnecessary

plugins/output/http.md
Signed-off-by: Masahiro Nakagawa <repeatedly@gmail.com>
Merge after release v1.7.0
=> Add out_http article

plugins/input/http.md, plugins/input/tcp.md
Add TLS mutual authentication to tcp and http
=> Add TLS mutual authentication to tcp and http

install/install-by-msi.md
Fixes https://github.com/fluent/fluentd/issues/2627.
=> Launching Fluentd Windows Service with net.exe or powershell

plugins/input/forward.md
=> Fix case on Config FIle link

guides/parse-syslog.md, guides/raspberrypi-cloud-data-logger.md
I tried to fix two broken links.
* `python logger` in https://docs.fluentd.org/how-to-guides/raspberrypi-cloud-data-logger
* `the grep plugin` in https://docs.fluentd.org/how-to-guides/parse-syslog
=> Fix some broken links

developer/api-plugin-output.md, guides/apache-to-minio.md
closes https://github.com/fluent/fluentd-docs-gitbook/issues/116
=> Fix broken style

container-deployment/kubernetes.md
Fixes https://github.com/fluent/fluentd-kubernetes-daemonset/issues/363.
=> container-deployment: kubernetes: Add TLS options for elasticsearch

deployment/system-config.md
ref: https://github.com/fluent/fluentd/pull/2730
=> change default value

configuration/parse-section.md
default value is true,
ref : https://github.com/fluent/fluentd/blob/master/lib/fluent/plugin/parser.rb\#L94
=> estimate_current_event field default value is not sync

plugins/output/rewrite_tag_filter.md
Signed-off-by: Yuta Iwama <ganmacs@gmail.com>
fix https://github.com/fluent/fluent-plugin-rewrite-tag-filter/issues/92
=> fix invalid regex

container-deployment/docker-compose.md
=> fix get started link

developer/api-plugin-helper-server.md, plugins/output/README.md
Proposed fix to https://github.com/fluent/fluentd-docs-gitbook/issues/152
api-plugin-helper-compat_parameters.md is under /developer/ directory
Signed-off-by: Christian Lacsina <christian.lacsina@rx-m.com>
=> fix compat_parameters helper link

SUMMARY.md, configuration/service_discovery-section.md, plugins/service_discovery/README.md, plugins/service_discovery/srv.md
ref: https://github.com/fluent/fluentd/pull/2876
=> Add srv sd document

plugins/filter/parser.md
fixed typo : injested -> injected
=> Fixed typo : injested -> injected for parser.md 

overview/logo.md
I fixed the URL of Full list of files .
=> fix url of logos

plugins/input/tcp.md
add security/client for in_tcp
=> add security/client for in_tcp

container-deployment/docker-compose.md, container-deployment/docker-logging-driver.md, container-deployment/install-by-docker.md, container-deployment/kubernetes.md
Container Deployment: Language and grammar fixes.
=> Container Deployment: Language and grammar fixes.

language/java.md, language/nodejs.md, language/perl.md, language/php.md, language/python.md, language/ruby.md, language/scala.md
Language API Section: Language and grammar updates.
=> Language API Section: Language and grammar updates.

deployment/command-line-option.md, deployment/failure-scenarios.md, deployment/fluentd-ui.md, deployment/high-availability.md, deployment/logging.md, deployment/monitoring-prometheus.md, deployment/monitoring-rest-api.md, deployment/monitoring.md, deployment/multi-process-workers.md, deployment/performance-tuning-single-process.md, deployment/plugin-management.md, deployment/rpc.md, deployment/signals.md, deployment/system-config.md, deployment/trouble-shooting.md
Deployment Section: Language and grammar updates.
=> Deployment Section: Language and grammar updates.

plugins/buffer/README.md, plugins/buffer/file.md, plugins/buffer/file_single.md, plugins/buffer/memory.md
Updates: Plugins - Buffer Section.
=> Updates: Plugins - Buffer Section.

plugins/storage/README.md, plugins/storage/local.md
=> Updates: Plugins - Storage.

plugins/service_discovery/README.md, plugins/service_discovery/file.md, plugins/service_discovery/srv.md, plugins/service_discovery/static.md
Updates: Plugins - Service Discovery.
=> Updates: Plugins - Service Discovery.

install/install-by-msi.md
Follow-up to fluent/fluentd#3037.
=> Add documentation for the --reg-winsvc-auto-start and --reg-winsvc-delay-start flags.

plugins/filter/README.md, plugins/filter/geoip.md, plugins/filter/grep.md, plugins/filter/parser.md, plugins/filter/record_transformer.md, plugins/filter/stdout.md
=> Updates: Plugins - Filter.

plugins/parser/README.md, plugins/parser/apache2.md, plugins/parser/apache_error.md, plugins/parser/csv.md, plugins/parser/json.md, plugins/parser/ltsv.md, plugins/parser/msgpack.md, plugins/parser/multiline.md, plugins/parser/nginx.md, plugins/parser/none.md, plugins/parser/regexp.md, plugins/parser/syslog.md, plugins/parser/tsv.md
=> Updates: Plugins - Parser.

plugins/output/README.md, plugins/output/copy.md, plugins/output/elasticsearch.md, plugins/output/exec.md, plugins/output/exec_filter.md, plugins/output/file.md, plugins/output/forward.md, plugins/output/http.md, plugins/output/kafka.md, plugins/output/mongo.md, plugins/output/mongo_replset.md, plugins/output/null.md, plugins/output/relabel.md, plugins/output/rewrite_tag_filter.md, plugins/output/roundrobin.md, plugins/output/s3.md, plugins/output/secondary_file.md, plugins/output/stdout.md, plugins/output/webhdfs.md
=> Updates: Plugins - Output.

install/install-by-gem.md
=> Drop unsupported options and use supported option from gem command example

plugins/output/mongo.md
Added `connection_string` parameter. #188
=> Added `connection_string` parameter. #188

deployment/logging.md
=> Fix unclosed label

install/install-by-msi.md
We'd already sent winget package addition request in:
https://github.com/microsoft/winget-pkgs/pull/3153
Package addition work's description is also published (but written in Japanese):
https://www.clear-code.com/blog/2020/8/25.html
=> msi: Add winget installation description

plugins/formatter/README.md, plugins/formatter/csv.md, plugins/formatter/hash.md, plugins/formatter/json.md, plugins/formatter/ltsv.md, plugins/formatter/out_file.md, plugins/formatter/single_value.md, plugins/formatter/tsv.md
* Add `newline` parameter descriptions.
* Add tsv formatter plugin documentation
=> 1.0: formatter: CRLF newline choice handling documentation

plugins/output/secondary_file.md
It is useful to mention about how to recover from secondary file.
=> output secondary_file: add howto to resend secondary file

output/rewrite_tag_filter.md
Closes https://github.com/fluent/fluentd-docs-gitbook/issues/273
=> 1.0: rewrite_tag_filter: Add example for k8s nested metadata handling

buffer/file.md, quickstart/faq.md
=> 0.12: Fix broken link to buffer documentation

quickstart/README.md
=> 0.12: fix missing linik to plugin overview

formatter/tsv.md
=> 1.0: add formatter tsv document

container-deployment/install-by-docker.md
=> Update container deployment explanation

parser/ltsv.md
It's introduced by https://github.com/fluent/fluentd/pull/3288
=> Add replacement config for formatter_ltsv

container-deployment/docker-logging-driver.md, filter/geoip.md, filter/stdout.md, how-to-guides/apache-to-minio.md, how-to-guides/splunk-like-grep-and-alert-email.md, output/exec_filter.md, output/http.md, output/secondary_file.md, plugin-helper-overview/api-plugin-helper-http_server.md, plugin-helper-overview/api-plugin-helper-storage.md
It should refer the latest version in 1.0 branch
=> Fix broken links except images

container-deployment/docker-compose.md
=> 1.0: add missing guide to parameters for Elasticsearch

storage/README.md
The information of supported plugin may help users understand
functionality.
=> 1.0: add storage plugins and supported plugins for example

storage/local.md
It is better to explain the behavior of the storage plugin.
=> 1.0: add storage plugin example

installation/install-from-source.md
A case of installation failure has been found
in some default mac environments.
Signed-off-by: daipom <reangoapyththeorem@gmail.com>
=> 1.0: add troubleshooting about installing

plugin-helper-overview/api-plugin-helper-service_discovery.md
Since v1.13.0 new helper API is introduced.
It makes supporting service_discovery easy.
ref. https://github.com/fluent/fluentd/pull/3299
=> 1.0: Update usage of new service discovery helper API

output/roundrobin.md
Using non standard output plugin makes a new user confused.
Closes: #325
=> 1.0: use core plugin for roundrobin example

input/tail.md
* Describe correct start position, it should be last read position if `pos_fileP is configured. Fix #336
* Revise other explanations to make easy to understand merits & demerits of this option.
=> in_tail: Revise read_from_head

deployment/command-line-option.md
Because storage plugin is supported.
=> 1.0: update outcome of fluent-plugin-generate -h
